### ISSUE TITLE
No loading screen

### ISSUE THREAD

**Issue by FedeDP** [eliasp/plasma-workspace-units#10]
Hi!
I'm trying out your units on my archlinux. Everything's fine, desktop loading with my ssd is insanely fast.
But i lost plasma 5 beautiful loading screen. Well, this is not a big problem because the loading is so fast that probably that screen would last 0,5s. But i'm wondering whether this was your will or it is a bug.
To be sure, i tried on another laptop without a ssd, and still no loading screen (but even on a slow hdd, using your units saved a lot of time)

Thanks for your work!

**Comment by eliasp** [comment]
Thanks for the feedback - please be aware, that this is currently more or less a playground and nothing supposed to be used in a productive environments due to its known limitations.

The splash screen is a WONTFIX for now, as it:
* takes more time to be displayed then the actual startup takes
* doesn't really indicate what's happening, as the systemd based startup is parallelized and the splashscreen is supposed to show a serial progress of the individual components being started

Should we ever want to display a splashscreen again, this would need some work on ksplashqml to support parallellized startups.

**Comment by FedeDP** [comment]
You're right, it provides a visual feedback about serial components startup...I didn't think about that.

By the way, even if this is not yet ready to be used in a productive environment, i really like to experiment, and it seems already quite safe (i had no problem for now).
Thank you very much!
