### ISSUE TITLE
Can't turn on/off wifi

### ISSUE THREAD

**Issue by AnAkIn1** [eliasp/plasma-workspace-units#11]
I am unable to turn on/off wifi in the network manager applet when I start the session with the systemd units. The tick box doesn't have any effect.

**Comment by ugis** [comment]
This is what I get when I try to disconnect my wi-fi http://i.imgur.com/rDRSozd.png

**Comment by eliasp** [comment]
This is a known limitation of the current user session experiments.
User session services are ran outside of any session context, which means, they're not linked to any logind session.
This means, that the processes run in a user-session service lack the `context=default` privilege required by most D-Bus system services (`org.freedesktop.NetworkManager`, `org.freedesktop.UDisks2`, …) for calling any methods on interfaces of those services.

This will be solved, once `kdbus` found its way into the Kernel and the model of a "user bus" instead of a "session bus" was established.

AFAIK there are some workarounds in polkit + dbus under development, trying to hack around this for the time being, but for now consider this "unsupported".
