### ISSUE TITLE
Shutdown just log out

### ISSUE THREAD

**Issue by AnAkIn1** [eliasp/plasma-workspace-units#12]
When I try to shutdown my computer, it just log outs of the session and goes back to SDDM.

**Comment by ugis** [comment]
Same problem here

**Comment by eliasp** [comment]
This is a known limitation of the current user session experiments.
User session services are ran outside of any session context, which means, they're not linked to any logind session.
This means, that the processes run in a user-session service lack the `context=default` privilege required by most D-Bus system services (`org.freedesktop.NetworkManager`, `org.freedesktop.UDisks2`, …) for calling any methods on interfaces of those services.

This will be solved, once `kdbus` found its way into the Kernel and the model of a "user bus" instead of a "session bus" was established.

AFAIK there are some workarounds in polkit + dbus under development, trying to hack around this for the time being, but for now consider this "unsupported".
